name: Test and Build Workflow
# This workflow is triggered on pull requests to main or a opendistro release branch
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  linux-build:
    # Job name
    name: Build Index Management
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses the setup-java Github action: https://github.com/actions/setup-java
      - name: Set Up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      # build index management
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build -Dopensearch.version=1.3.0-SNAPSHOT
      - name: Upload failed logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: build/testclusters/integTest-*/logs/*
      - name: Create Artifact Path
        run: |
          mkdir -p index-management-artifacts
          cp ./build/distributions/*.zip index-management-artifacts        
      - name: Uploads coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      # This step uses the upload-artifact Github action: https://github.com/actions/upload-artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: index-management-plugin
          path: index-management-artifacts
  windows-build:
    # Job name
    name: Build Index Management
    # This job runs on Windows
    runs-on: windows-latest
    steps:
      # This step uses the setup-java Github action: https://github.com/actions/setup-java
      - name: Set Up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      # build index management
      - name: Checkout Branch
        uses: actions/checkout@v2
      # This step creates a link to the X: mounted drive, which makes the path short enough to work on windows
      - name: Shorten Path
        run: subst 'X:' .
      - name: Build with Gradle
        working-directory: 'X:'
        run: ./gradlew.bat build -D"opensearch.version=1.2.0-SNAPSHOT"
        env:
          _JAVA_OPTIONS: -Xmx4096M
      - name: Upload failed logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: build/testclusters/integTest-*/logs/*
      - name: Create Artifact Path
        run: |
          mkdir -p index-management-artifacts
          cp ./build/distributions/*.zip index-management-artifacts
      - name: Uploads coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      # This step uses the upload-artifact Github action: https://github.com/actions/upload-artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: index-management-plugin
          path: index-management-artifacts
